name: totalsegmentator-rtstructure
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dcm2niix
  - pydicom
  - jupyterlab
  - pip
  - pip :
    - scikit-learn==1.2.0
    - TotalSegmentator==1.5.5
    - monai-deploy-app-sdk==0.5.0
    - matplotlib==3.6.2
    - typeguard~=2.12.1 # Work around MONAI requirements.txt bug that picks up the wrong typeguard version
    - highdicom
    - rt-utils
    - torch>=1.12.0

